import type { Config } from 'tailwindcss';

/**
 * Lumina Learn — shared Tailwind preset.
 * Ported verbatim from design/tokens/tokens.json and the design/screens/* <style> blocks.
 * DO NOT change color/typography values without a design decision (see design/design.md).
 */
const preset: Omit<Config, 'content'> = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#5e41d0',
        'on-primary': '#ffffff',
        'primary-container': '#775ceb',
        'on-primary-container': '#fffbff',
        'primary-fixed': '#e6deff',
        'primary-fixed-dim': '#cabeff',
        'on-primary-fixed': '#1c0062',
        'on-primary-fixed-variant': '#4825ba',
        'inverse-primary': '#cabeff',
        secondary: '#a3336c',
        'on-secondary': '#ffffff',
        'secondary-container': '#ff7db8',
        'on-secondary-container': '#780b4a',
        'secondary-fixed': '#ffd9e5',
        'secondary-fixed-dim': '#ffb0cf',
        'on-secondary-fixed': '#3d0023',
        'on-secondary-fixed-variant': '#841853',
        tertiary: '#00647c',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#007f9d',
        'on-tertiary-container': '#fafdff',
        'tertiary-fixed': '#b7eaff',
        'tertiary-fixed-dim': '#5bd5fc',
        'on-tertiary-fixed': '#001f28',
        'on-tertiary-fixed-variant': '#004e61',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fcf8ff',
        'on-background': '#1a1a27',
        surface: '#fcf8ff',
        'surface-dim': '#dad8e9',
        'surface-bright': '#fcf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f2ff',
        'surface-container': '#eeecfe',
        'surface-container-high': '#e9e6f8',
        'surface-container-highest': '#e3e0f2',
        'on-surface': '#1a1a27',
        'on-surface-variant': '#484554',
        'surface-variant': '#e3e0f2',
        'surface-tint': '#6043d3',
        'inverse-surface': '#2f2f3c',
        'inverse-on-surface': '#f2efff',
        outline: '#797586',
        'outline-variant': '#c9c4d7',
      },
      borderRadius: {
        DEFAULT: '1rem',
        sm: '0.5rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'sidebar-width': '260px',
        'container-padding': '32px',
        gutter: '24px',
        'card-gap': '20px',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-bold': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        display: ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-bold': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};

export default preset;
